title: "Kyle Lyon"
url: "https://lyon.computer"
baseurl: ""
permalink: pretty
markdown: kramdown
timezone: America/Denver
defaults:
  - scope:
      path: ""
    values:
      layout: null

exclude:
  - README.md
  - node_modules
  - vendor
  - package.json
  - package-lock.json

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

